export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const SET_ACTIVE_USER = "SET_ACTIVE_USER";
export const SET_AUTH_EXPIRATION = "SET_AUTH_EXPIRATION";
export const LOGOUT_CURRENT_USER = "LOGOUT_CURRENT_USER";

